version: "2"

volumes:
  # for persistence between restarts
  mongo_data: {}

services:
  web:
    build: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - variables.env
    links:
      - mongo-db
    depends_on:
      - mongo-db
    volumes:
      - .:/project
    working_dir: /project
    command: python app.py

  mongo-db:
    image: mongo:4.1.1
    logging:
      driver: none
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
